name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Change directory to zjazd3
      - name: Change working directory to zjazd3
        run: cd zjazd3

      # 4. Run tests
      - name: Run tests
        working-directory: zjazd3
        run: python -m unittest discover -s tests -p "*.py"
